
workflows:
  android-apk:
    name: Build Android APK
    max_build_duration: 60
    environment:
      vars:
        NODE_ENV: development
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Install EAS CLI
        script: npm install -g eas-cli
      - name: Prebuild Expo
        script: npx expo prebuild
      - name: Build APK
        script: eas build -p android --profile preview --non-interactive
    artifacts:
      - build/android/**/*.apk
    publishing:
      email:
        recipients:
          - ton.email@domaine.com
