

workflows:
  android:
    name: Build Android APK & AAB
    environment:
      vars:
        EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        ANDROID_KEYSTORE_PATH: "@shopia__shopai.jks"
        ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
        ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
        ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
    scripts:
      - name: Install dependencies
        script: npm ci

      - name: Prebuild Expo
        script: npx expo prebuild --no-install

      - name: Build APK
        script: npx eas build --platform android --profile production-apk --non-interactive

      - name: Build AAB
        script: npx eas build --platform android --profile production-aab --non-interactive

    artifacts:
      - build/**/*.apk
      - build/**/*.aab
