workflows:
  android:
    name: Build Android APK
    environment:
      vars:
        EXPO_TOKEN: "Y-39ShqJWGt4w1WgdlZe0amzC_0XTm0VY5EDxj1N"
        ANDROID_KEYSTORE_PATH: "@shopia__shopai.jks"
        ANDROID_KEYSTORE_PASSWORD: "823c916b5933495a94b83bdd07aacb3b"
        ANDROID_KEY_ALIAS: "c912d60ee44b7b143187a4a9e9e84d07"
        ANDROID_KEY_PASSWORD: "4a18a087078d873a6ffbed838fa09eb1"
    scripts:
      - name: Setup Node & NPM
        script: |
          echo "Node version:"
          node -v
          echo "NPM version:"
          npm -v
          npm config set script-shell bash
      - name: Install dependencies
        script: npm ci
      - name: Prebuild Expo
        script: npx expo prebuild --no-install
      - name: Build APK
        script: npx eas build --platform android --non-interactive --profile preview
    artifacts:
      - build/**/*.apk
