

workflows:
  android-apk:
    name: Build Android APK
    max_build_duration: 5
    environment:
      vars:
        NODE_ENV: development
    scripts:
      - name: Install dependencies
        script: yarn install
      - name: Prebuild Expo
        script: npx expo prebuild
      - name: Build APK
        script: npx eas build -p android --profile preview --non-interactive
    artifacts:
      - build/android/**/*.apk
