workflows:
  android-apk:
    name: Build Android APK
    max_build_duration: 60
    environment:
      vars:
        NODE_ENV: development
        EXPO_TOKEN: Y-39ShqJWGt4w1WgdlZe0amzC_0XTm0VY5EDxj1N
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Prebuild Expo
        script: npx expo prebuild
      - name: Build APK
        script: npx eas build -p android --non-interactive
    artifacts:
      - build/android/**/*.apk
